"""baseline

Revision ID: e61db2bd6234
Revises: 
Create Date: 2026-02-09 07:18:30.193877

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import postgresql

revision = 'e61db2bd6234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_bank_accounts_provider_external_id')
    )
    op.create_table('cost_allocations',
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_net_cents', sa.Integer(), nullable=False),
    sa.Column('amount_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('input_tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('receipt_upload_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_counters',
    sa.Column('doc_type', sa.Enum('PURCHASE_CREDIT_NOTE', 'SALES_INVOICE', 'SALES_CORRECTION', name='document_type'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('doc_type', 'year', name='pk_document_counters')
    )
    op.create_table('fba_shipments',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SHIPPED', 'RECEIVED', name='fba_shipment_status'), nullable=False),
    sa.Column('carrier', sa.String(length=80), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('shipping_cost_cents', sa.Integer(), nullable=False),
    sa.Column('cost_distribution_method', sa.Enum('EQUAL', 'PURCHASE_PRICE_WEIGHTED', name='fba_cost_distribution_method'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fba_shipments_status'), 'fba_shipments', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('account', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_products',
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('variant', sa.String(length=80), nullable=False),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('asin', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'title', 'platform', 'region', 'variant', name='uq_master_product_identity'),
    sa.UniqueConstraint('sku', name='uq_master_product_sku')
    )
    op.create_table('opex_expenses',
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PACKAGING', 'POSTAGE', 'SOFTWARE', 'OFFICE', 'CONSULTING', 'FEES', 'OTHER', name='opex_category'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_net_cents', sa.Integer(), nullable=False),
    sa.Column('amount_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('input_tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('receipt_upload_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('kind', sa.Enum('PRIVATE_DIFF', 'COMMERCIAL_REGULAR', name='purchase_kind'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=False),
    sa.Column('counterparty_address', sa.Text(), nullable=True),
    sa.Column('counterparty_birthdate', sa.Date(), nullable=True),
    sa.Column('counterparty_id_number', sa.String(length=80), nullable=True),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_cost_cents', sa.Integer(), nullable=False),
    sa.Column('buyer_protection_fee_cents', sa.Integer(), nullable=False),
    sa.Column('total_net_cents', sa.Integer(), nullable=False),
    sa.Column('total_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('source_platform', sa.String(length=120), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_number', sa.String(length=64), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('external_invoice_number', sa.String(length=128), nullable=True),
    sa.Column('receipt_upload_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_orders',
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.Enum('EBAY', 'AMAZON', 'WILLHABEN', 'OTHER', name='order_channel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('shipping_gross_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_regular_gross_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_regular_net_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_regular_tax_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_margin_gross_cents', sa.Integer(), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('invoice_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('booked_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('remittance_information', sa.Text(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'external_id', name='uq_bank_tx_account_external_id')
    )
    op.create_index('ix_bank_transactions_account_booked_date', 'bank_transactions', ['bank_account_id', 'booked_date'], unique=False)
    op.create_index('ix_bank_transactions_booked_date', 'bank_transactions', ['booked_date'], unique=False)
    op.create_table('mileage_logs',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('start_location', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Enum('BUYING', 'POST', 'MATERIAL', 'OTHER', name='mileage_purpose'), nullable=False),
    sa.Column('purpose_text', sa.String(length=300), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('rate_cents_per_km', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_attachments',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'upload_path', name='uq_purchase_attachment_path')
    )
    op.create_index(op.f('ix_purchase_attachments_purchase_id'), 'purchase_attachments', ['purchase_id'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'ACCEPTABLE', 'DEFECT', name='inventory_condition'), nullable=False),
    sa.Column('purchase_type', sa.Enum('DIFF', 'REGULAR', name='purchase_type'), nullable=False),
    sa.Column('purchase_price_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_allocated_cents', sa.Integer(), nullable=False),
    sa.Column('buyer_protection_fee_allocated_cents', sa.Integer(), nullable=False),
    sa.Column('purchase_price_net_cents', sa.Integer(), nullable=False),
    sa.Column('purchase_price_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_corrections',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('correction_date', sa.Date(), nullable=False),
    sa.Column('correction_number', sa.String(length=64), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('refund_gross_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_gross_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_regular_gross_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_regular_net_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_regular_tax_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_margin_gross_cents', sa.Integer(), nullable=False),
    sa.Column('payment_source', sa.Enum('CASH', 'BANK', name='payment_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correction_number')
    )
    op.create_table('bank_transaction_purchases',
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_transaction_id', 'purchase_id')
    )
    op.create_index('ix_bank_transaction_purchases_bank_transaction_id', 'bank_transaction_purchases', ['bank_transaction_id'], unique=False)
    op.create_index('ix_bank_transaction_purchases_purchase_id', 'bank_transaction_purchases', ['purchase_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('purchase_line_id', sa.UUID(), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'ACCEPTABLE', 'DEFECT', name='inventory_condition'), nullable=False),
    sa.Column('purchase_type', sa.Enum('DIFF', 'REGULAR', name='purchase_type'), nullable=False),
    sa.Column('purchase_price_cents', sa.Integer(), nullable=False),
    sa.Column('allocated_costs_cents', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AVAILABLE', 'FBA_INBOUND', 'FBA_WAREHOUSE', 'RESERVED', 'SOLD', 'RETURNED', 'DISCREPANCY', 'LOST', name='inventory_status'), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_line_id')
    )
    op.create_table('mileage_log_purchases',
    sa.Column('mileage_log_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mileage_log_id'], ['mileage_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mileage_log_id', 'purchase_id')
    )
    op.create_index('ix_mileage_log_purchases_purchase_id', 'mileage_log_purchases', ['purchase_id'], unique=False)
    op.create_table('cost_allocation_lines',
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_net_cents', sa.Integer(), nullable=False),
    sa.Column('amount_tax_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['cost_allocations.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fba_shipment_items',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('allocated_shipping_cost_cents', sa.Integer(), nullable=False),
    sa.Column('received_status', sa.Enum('DRAFT', 'AVAILABLE', 'FBA_INBOUND', 'FBA_WAREHOUSE', 'RESERVED', 'SOLD', 'RETURNED', 'DISCREPANCY', 'LOST', name='inventory_status'), nullable=True),
    sa.Column('discrepancy_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['fba_shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'inventory_item_id', name='uq_fba_shipment_item')
    )
    op.create_index(op.f('ix_fba_shipment_items_inventory_item_id'), 'fba_shipment_items', ['inventory_item_id'], unique=False)
    op.create_table('inventory_item_images',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'upload_path', name='uq_inventory_item_image_path')
    )
    op.create_index(op.f('ix_inventory_item_images_inventory_item_id'), 'inventory_item_images', ['inventory_item_id'], unique=False)
    op.create_table('sales_correction_lines',
    sa.Column('correction_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('RESTOCK', 'WRITE_OFF', name='return_action'), nullable=False),
    sa.Column('purchase_type', sa.Enum('DIFF', 'REGULAR', name='purchase_type'), nullable=False),
    sa.Column('refund_gross_cents', sa.Integer(), nullable=False),
    sa.Column('refund_net_cents', sa.Integer(), nullable=False),
    sa.Column('refund_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('shipping_refund_allocated_cents', sa.Integer(), nullable=False),
    sa.Column('margin_vat_adjustment_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['correction_id'], ['sales_corrections.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id')
    )
    op.create_table('sales_order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_type', sa.Enum('DIFF', 'REGULAR', name='purchase_type'), nullable=False),
    sa.Column('sale_gross_cents', sa.Integer(), nullable=False),
    sa.Column('sale_net_cents', sa.Integer(), nullable=False),
    sa.Column('sale_tax_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate_bp', sa.Integer(), nullable=False),
    sa.Column('shipping_allocated_cents', sa.Integer(), nullable=False),
    sa.Column('cost_basis_cents', sa.Integer(), nullable=False),
    sa.Column('margin_gross_cents', sa.Integer(), nullable=False),
    sa.Column('margin_net_cents', sa.Integer(), nullable=False),
    sa.Column('margin_tax_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_lines')
    op.drop_table('sales_correction_lines')
    op.drop_index(op.f('ix_inventory_item_images_inventory_item_id'), table_name='inventory_item_images')
    op.drop_table('inventory_item_images')
    op.drop_index(op.f('ix_fba_shipment_items_inventory_item_id'), table_name='fba_shipment_items')
    op.drop_table('fba_shipment_items')
    op.drop_table('cost_allocation_lines')
    op.drop_index('ix_mileage_log_purchases_purchase_id', table_name='mileage_log_purchases')
    op.drop_table('mileage_log_purchases')
    op.drop_table('inventory_items')
    op.drop_index('ix_bank_transaction_purchases_purchase_id', table_name='bank_transaction_purchases')
    op.drop_index('ix_bank_transaction_purchases_bank_transaction_id', table_name='bank_transaction_purchases')
    op.drop_table('bank_transaction_purchases')
    op.drop_table('sales_corrections')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_purchase_attachments_purchase_id'), table_name='purchase_attachments')
    op.drop_table('purchase_attachments')
    op.drop_table('mileage_logs')
    op.drop_index('ix_bank_transactions_booked_date', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_account_booked_date', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('sales_orders')
    op.drop_table('purchases')
    op.drop_table('opex_expenses')
    op.drop_table('master_products')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_fba_shipments_status'), table_name='fba_shipments')
    op.drop_table('fba_shipments')
    op.drop_table('document_counters')
    op.drop_table('cost_allocations')
    op.drop_table('bank_accounts')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

